version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ../server
    container_name: weather_backend
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
      WEATHER_API_KEY: ${WEATHER_API_KEY}
    volumes:
      - ./backend:/home/node
    ports:
      - '3000:3000'
    command: sh -c "npx prisma migrate deploy && npm run start:dev"
    # command: sh -c "npx prisma migrate deploy && npm run start:prod"

volumes:
  pgdata:
